creation_rules:
  - age: >-
      age1v8wxuccevj8gc9yynsy0wu8yecs672y9q8nd4v7c8remn7kqvs8qx0sgsu,
      age1n5whqfcruaklvuds274jxd0wcj8yh07lnklk2u5mj5lscpgnssqq2x4xtw,
      age124sw4mhg3w06qm007ercnxrpw4czarp3dvrzjmc8f2xnpsdeta4saq5dla
